version: "3.9"
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code  # instead of copied sources (see Dockerfile) mount development repo
      - ./db.sqlite3:/code/db.sqlite3  # reuse development DB
