version: "3.9"
services:
  web:
    build: .  # act on Dockerfile in current dir
    ports:
      - "8007:8000"
    environment:
      - PYTHONDEBUG  # values will come from .env
      - DJANGO_SUPERUSER_USERNAME  # folowing 3 envvars for: python manage.py createsuperuser --noinput
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - EMAIL_SMTP_PORT
      - PYTHONUNBUFFERED=1 # no buffering stdout/stderr so Django logs are real time into container console
      - PYTHONDONTWRITEBYTECODE=1  # no .pyc
      - CELERY_BROKER_URL
    depends_on:
      - broker
    links:
      - broker
  mail:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "1025:1025"
      - "8025:8025"
  broker:
    image: "rabbitmq:3.9.13-management"
#    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
      - "5672:5672"    # queue
      - "15672:15672"  # Web UI: http://container-ip:15672
#  worker:
#    build:
#      context: ./api
#    hostname: worker
#    entrypoint: celery
#    command: -A celery_app.celery worker --loglevel=info
#    volumes:
#      - ./api:/app
#    links:
#      - redis
#    depends_on:
#      - redis
