version: "3.9"
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code  # instead of copied sources (see Dockerfile) mount development repo
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"